# Generated by Django 3.2.4 on 2022-02-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkpermitExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('sub_activity', models.CharField(max_length=255)),
                ('work_permit', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=400, null=True)),
                ('manager', models.CharField(max_length=255)),
                ('assignee', models.CharField(max_length=255)),
            ],
        ),
    ]
